"""
PDF Report Generator for Agent Ada
Generates professional daily market reports in PDF format
"""
import io
import logging
import unicodedata
from datetime import datetime
from typing import Dict, List, Optional, Any
import streamlit as st

# Setup logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Try to import PDF libraries
try:
    from fpdf import FPDF
    FPDF_AVAILABLE = True
    logger.info("✅ fpdf2 library available")
except ImportError:
    FPDF_AVAILABLE = False
    logger.warning("⚠️ fpdf2 not installed. Run: pip install fpdf2")


def vietnamese_to_ascii(text: str) -> str:
    """
    Convert Vietnamese text to ASCII by removing diacritics
    """
    # Vietnamese character mapping
    vietnamese_map = {
        'à': 'a', 'á': 'a', 'ả': 'a', 'ã': 'a', 'ạ': 'a',
        'ă': 'a', 'ằ': 'a', 'ắ': 'a', 'ẳ': 'a', 'ẵ': 'a', 'ặ': 'a',
        'â': 'a', 'ầ': 'a', 'ấ': 'a', 'ẩ': 'a', 'ẫ': 'a', 'ậ': 'a',
        'đ': 'd',
        'è': 'e', 'é': 'e', 'ẻ': 'e', 'ẽ': 'e', 'ẹ': 'e',
        'ê': 'e', 'ề': 'e', 'ế': 'e', 'ể': 'e', 'ễ': 'e', 'ệ': 'e',
        'ì': 'i', 'í': 'i', 'ỉ': 'i', 'ĩ': 'i', 'ị': 'i',
        'ò': 'o', 'ó': 'o', 'ỏ': 'o', 'õ': 'o', 'ọ': 'o',
        'ô': 'o', 'ồ': 'o', 'ố': 'o', 'ổ': 'o', 'ỗ': 'o', 'ộ': 'o',
        'ơ': 'o', 'ờ': 'o', 'ớ': 'o', 'ở': 'o', 'ỡ': 'o', 'ợ': 'o',
        'ù': 'u', 'ú': 'u', 'ủ': 'u', 'ũ': 'u', 'ụ': 'u',
        'ư': 'u', 'ừ': 'u', 'ứ': 'u', 'ử': 'u', 'ữ': 'u', 'ự': 'u',
        'ỳ': 'y', 'ý': 'y', 'ỷ': 'y', 'ỹ': 'y', 'ỵ': 'y',
    }
    
    # Convert to lowercase, replace Vietnamese chars
    result = text.lower()
    for vn_char, ascii_char in vietnamese_map.items():
        result = result.replace(vn_char, ascii_char)
        result = result.replace(vn_char.upper(), ascii_char.upper())
    
    # Remove any remaining non-ASCII
    result = unicodedata.normalize('NFKD', result).encode('ascii', 'ignore').decode('ascii')
    
    # Restore case for first letter
    if text and text[0].isupper() and result:
        result = result[0].upper() + result[1:]
    
    return result


class AgentAdaPDF(FPDF):
    """Custom PDF class with Ada branding"""
    
    def __init__(self):
        super().__init__()
        self.set_auto_page_break(auto=True, margin=15)
        
        # Try to use built-in Unicode fonts from fpdf2
        # Arial Unicode MS or use core fonts with unicode=True
        self.default_font = 'Helvetica'
        self.unicode_support = False
        
        logger.info("⚠️ Using Helvetica - Vietnamese will be transliterated")
        
    def header(self):
        """Page header"""
        self.set_font(self.default_font, 'B', 12)
        self.set_text_color(31, 119, 180)  # Blue
        self.cell(0, 10, 'Agent Ada - Daily Market Report', align='C', new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(31, 119, 180)
        self.line(10, 20, 200, 20)
        self.ln(5)
        
    def footer(self):
        """Page footer"""
        self.set_y(-15)
        self.set_font(self.default_font, 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by Agent Ada | For HFM Brokers', align='C')
    
    def chapter_title(self, title: str):
        """Add chapter title"""
        self.set_font(self.default_font, 'B', 14)
        self.set_text_color(0, 0, 0)
        self.cell(0, 10, title, new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(200, 200, 200)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(5)
        
    def section_title(self, title: str):
        """Add section title"""
        self.set_font(self.default_font, 'B', 11)
        self.set_text_color(31, 119, 180)
        self.cell(0, 8, title, new_x="LMARGIN", new_y="NEXT")
        self.ln(2)
        
    def body_text(self, text: str):
        """Add body text with Vietnamese support"""
        self.set_font(self.default_font, '', 10)
        self.set_text_color(0, 0, 0)
        # Convert Vietnamese to ASCII for PDF compatibility
        safe_text = vietnamese_to_ascii(text)
        self.multi_cell(0, 6, safe_text)
        self.ln(2)
        
    def bullet_point(self, text: str, indent: int = 10):
        """Add bullet point with Vietnamese support"""
        self.set_font(self.default_font, '', 10)
        self.set_text_color(0, 0, 0)
        self.set_x(indent)
        # Convert Vietnamese to ASCII for PDF compatibility
        safe_text = vietnamese_to_ascii(text)
        self.multi_cell(0, 6, f"• {safe_text}")
        
    def metric_row(self, label: str, value: str, change: str = None):
        """Add metric row"""
        self.set_font(self.default_font, '', 10)
        self.set_text_color(0, 0, 0)
        self.cell(60, 6, label)
        self.set_font(self.default_font, 'B', 10)
        self.cell(40, 6, str(value))
        if change:
            if change.startswith('+') or (change[0].isdigit() and float(change) > 0):
                self.set_text_color(0, 128, 0)  # Green
            elif change.startswith('-'):
                self.set_text_color(255, 0, 0)  # Red
            else:
                self.set_text_color(128, 128, 128)  # Gray
            self.cell(30, 6, change)
            self.set_text_color(0, 0, 0)
        self.ln()


class ReportPDFGenerator:
    """
    Generate PDF reports from Agent Ada data
    """
    
    def __init__(self):
        if not FPDF_AVAILABLE:
            raise ImportError("fpdf2 library required. Install with: pip install fpdf2")
    
    def generate_daily_report(
        self,
        date: str,
        highlights: List[str],
        risk_sentiment: Dict[str, float],
        market_snapshot: Dict[str, Dict],
        ai_analysis: str = None,
        fund_flows: Dict = None,
        economic_calendar: List[Dict] = None
    ) -> bytes:
        """
        Generate complete daily market report PDF
        
        Args:
            date: Report date
            highlights: List of overnight highlights
            risk_sentiment: VIX, DXY, US10Y values
            market_snapshot: Market data by ticker
            ai_analysis: AI-generated analysis text
            fund_flows: Gold/Bitcoin ETF flows
            economic_calendar: Economic events
            
        Returns:
            PDF file as bytes
        """
        pdf = AgentAdaPDF()
        pdf.add_page()
        
        # Title
        pdf.set_font(pdf.default_font, 'B', 20)
        pdf.set_text_color(31, 119, 180)
        pdf.cell(0, 15, f"DAILY MARKET REPORT", align='C', new_x="LMARGIN", new_y="NEXT")
        pdf.set_font(pdf.default_font, '', 12)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(0, 8, date, align='C', new_x="LMARGIN", new_y="NEXT")
        pdf.ln(10)
        
        # Section 1: Executive Summary
        pdf.chapter_title("1. EXECUTIVE SUMMARY")
        
        pdf.section_title("Overnight Highlights")
        for highlight in highlights[:5]:
            pdf.bullet_point(highlight)
        pdf.ln(5)
        
        pdf.section_title("Risk Sentiment")
        pdf.metric_row("VIX (Volatility)", f"{risk_sentiment.get('vix', 0):.2f}")
        pdf.metric_row("DXY (USD Index)", f"{risk_sentiment.get('dxy', 0):.2f}")
        pdf.metric_row("US 10Y Yield", f"{risk_sentiment.get('us10y', 0):.2f}%")
        pdf.ln(5)
        
        # Section 2: Market Snapshot
        pdf.chapter_title("2. MARKET SNAPSHOT")
        
        # Table header
        pdf.set_font(pdf.default_font, 'B', 10)
        pdf.set_fill_color(240, 240, 240)
        pdf.cell(40, 8, "Asset", border=1, fill=True)
        pdf.cell(35, 8, "Last", border=1, fill=True)
        pdf.cell(30, 8, "D1 %", border=1, fill=True)
        pdf.cell(30, 8, "WTD %", border=1, fill=True)
        pdf.cell(30, 8, "MTD %", border=1, fill=True)
        pdf.ln()
        
        # Table rows
        pdf.set_font(pdf.default_font, '', 9)
        for ticker, data in market_snapshot.items():
            if isinstance(data, dict):
                pdf.cell(40, 7, ticker[:15], border=1)
                pdf.cell(35, 7, f"${data.get('last', 0):.2f}", border=1)
                
                # D1 with color
                d1 = data.get('d1', 0)
                pdf.cell(30, 7, f"{d1:+.2f}%", border=1)
                
                wtd = data.get('wtd', 0)
                pdf.cell(30, 7, f"{wtd:+.2f}%", border=1)
                
                mtd = data.get('mtd', 0)
                pdf.cell(30, 7, f"{mtd:+.2f}%", border=1)
                pdf.ln()
        
        pdf.ln(5)
        
        # Section 3: Fund Flows (if available)
        if fund_flows:
            pdf.chapter_title("3. ETF FUND FLOWS")
            
            if fund_flows.get("gold"):
                pdf.section_title("Gold ETFs")
                gold = fund_flows["gold"]
                pdf.body_text(f"Daily Flow: ${gold.get('total_flow_usd', 0)/1e6:.1f}M")
                pdf.body_text(f"Date: {gold.get('date', 'N/A')}")
                pdf.ln(3)
            
            if fund_flows.get("bitcoin"):
                pdf.section_title("Bitcoin ETFs")
                btc = fund_flows["bitcoin"]
                pdf.body_text(f"Daily Flow: ${btc.get('total_flow_usd', 0)/1e6:.1f}M")
                pdf.body_text(f"Date: {btc.get('date', 'N/A')}")
                pdf.ln(3)
        
        # Section 4: AI Analysis (if available)
        if ai_analysis:
            pdf.add_page()
            pdf.chapter_title("4. ADA'S ANALYSIS")
            pdf.body_text(ai_analysis)
            pdf.ln(5)
        
        # Section 5: Economic Calendar (if available)
        if economic_calendar:
            pdf.chapter_title("5. ECONOMIC CALENDAR")
            
            pdf.set_font(pdf.default_font, 'B', 9)
            pdf.set_fill_color(240, 240, 240)
            pdf.cell(25, 7, "Time", border=1, fill=True)
            pdf.cell(25, 7, "Region", border=1, fill=True)
            pdf.cell(80, 7, "Event", border=1, fill=True)
            pdf.cell(25, 7, "Impact", border=1, fill=True)
            pdf.ln()
            
            pdf.set_font(pdf.default_font, '', 8)
            for event in economic_calendar[:10]:
                pdf.cell(25, 6, str(event.get('time_local', ''))[:8], border=1)
                pdf.cell(25, 6, str(event.get('region', ''))[:10], border=1)
                event_text = str(event.get('event', ''))[:35]
                safe_event = vietnamese_to_ascii(event_text)
                pdf.cell(80, 6, safe_event, border=1)
                pdf.cell(25, 6, str(event.get('impact', '')), border=1)
                pdf.ln()
        
        # Disclaimer
        pdf.add_page()
        pdf.chapter_title("DISCLAIMER")
        pdf.set_font(pdf.default_font, 'I', 9)
        pdf.set_text_color(100, 100, 100)
        disclaimer = """
This report is for informational purposes only and does not constitute investment advice. 
The information contained herein is believed to be reliable but is not guaranteed. 
Past performance is not indicative of future results. Trading CFDs involves significant 
risk of loss and may not be suitable for all investors.

Generated by Agent Ada for HFM Brokers.
        """
        pdf.multi_cell(0, 5, disclaimer.strip())
        
        # Generate PDF bytes
        return bytes(pdf.output())
    
    def generate_asset_report(
        self,
        asset: str,
        snapshot: Dict,
        drivers: List[str],
        trade_plan: Dict,
        ai_analysis: str = None
    ) -> bytes:
        """
        Generate single asset analysis PDF
        
        Args:
            asset: Asset name (e.g., "XAUUSD")
            snapshot: Price and technical data
            drivers: List of price drivers
            trade_plan: Trading plan with bias, levels, etc.
            ai_analysis: AI-generated commentary
            
        Returns:
            PDF file as bytes
        """
        pdf = AgentAdaPDF()
        pdf.add_page()
        
        # Title
        pdf.set_font(pdf.default_font, 'B', 18)
        pdf.set_text_color(31, 119, 180)
        pdf.cell(0, 12, f"{asset} ANALYSIS", align='C', new_x="LMARGIN", new_y="NEXT")
        pdf.set_font(pdf.default_font, '', 10)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(0, 6, datetime.now().strftime("%Y-%m-%d %H:%M UTC"), align='C', new_x="LMARGIN", new_y="NEXT")
        pdf.ln(10)
        
        # Price Snapshot
        pdf.section_title("Price Snapshot")
        pdf.metric_row("Last Price", f"${snapshot.get('last', 0):.2f}")
        pdf.metric_row("Daily Change", f"{snapshot.get('pct_d1', 0):+.2f}%")
        pdf.metric_row("ATR(14)", f"${snapshot.get('atr', 0):.2f}")
        pdf.metric_row("MA20", f"${snapshot.get('ma20', 0):.2f}")
        pdf.metric_row("MA50", f"${snapshot.get('ma50', 0):.2f}")
        pdf.ln(5)
        
        # Drivers
        pdf.section_title("Key Drivers")
        for driver in drivers:
            pdf.bullet_point(driver)
        pdf.ln(5)
        
        # Trade Plan
        pdf.section_title("Trade Plan")
        pdf.metric_row("Bias", trade_plan.get('bias', 'Neutral'))
        pdf.metric_row("Trigger", trade_plan.get('trigger', 'N/A'))
        pdf.metric_row("Invalidation", trade_plan.get('invalidation', 'N/A'))
        pdf.metric_row("Timeframe", trade_plan.get('timeframe', 'D1'))
        
        levels = trade_plan.get('levels', {})
        if levels:
            pdf.ln(3)
            pdf.body_text(f"R1: {levels.get('R1', 'N/A')} | R2: {levels.get('R2', 'N/A')}")
            pdf.body_text(f"S1: {levels.get('S1', 'N/A')} | S2: {levels.get('S2', 'N/A')}")
        pdf.ln(5)
        
        # AI Analysis
        if ai_analysis:
            pdf.section_title("Ada's Commentary")
            pdf.body_text(ai_analysis)
        
        return bytes(pdf.output())


# ==================== STREAMLIT INTEGRATION ====================

def render_pdf_download_button(
    report_data: Dict,
    button_label: str = "📥 Tải PDF Report",
    filename: str = None
):
    """
    Render PDF download button in Streamlit
    
    Args:
        report_data: Dictionary with report data
        button_label: Button text
        filename: Output filename (auto-generated if None)
    """
    if not FPDF_AVAILABLE:
        st.warning("⚠️ PDF export requires fpdf2. Install with: `pip install fpdf2`")
        return
    
    try:
        generator = ReportPDFGenerator()
        
        pdf_bytes = generator.generate_daily_report(
            date=report_data.get('date', datetime.now().strftime("%Y-%m-%d")),
            highlights=report_data.get('highlights', []),
            risk_sentiment=report_data.get('risk_sentiment', {}),
            market_snapshot=report_data.get('market_snapshot', {}),
            ai_analysis=report_data.get('ai_analysis'),
            fund_flows=report_data.get('fund_flows'),
            economic_calendar=report_data.get('economic_calendar')
        )
        
        if filename is None:
            filename = f"ada_report_{datetime.now().strftime('%Y%m%d_%H%M')}.pdf"
        
        st.download_button(
            label=button_label,
            data=pdf_bytes,
            file_name=filename,
            mime="application/pdf"
        )
        
    except Exception as e:
        st.error(f"❌ Error generating PDF: {e}")
        logger.error(f"PDF generation error: {e}")


def check_pdf_available() -> bool:
    """Check if PDF generation is available"""
    return FPDF_AVAILABLE
